#
# Copyright (c) 2023, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at http://oss.oracle.com/licenses/upl.
#

apiVersion: database.oracle.com/v4
kind: DataguardBroker
metadata:
  name: dataguardbroker-sample
  namespace: default
spec:
  
  ## Primary database resource reference.
  primaryDatabaseRef: "sidb-sample"

  ## Standby SingleInstanceDatabase resource names to add to the Data Guard configuration.
  standbyDatabaseRefs:
  #  - standbydatabase-sample
  #  - standbydatabase-sample1

  ## Service exposure mode for the broker service.
  ## When false, the service is created as NodePort. When true, it is created as LoadBalancer.
  loadBalancer: false

  ## Protection mode for the Data Guard configuration. Valid values: MaxAvailability or MaxPerformance.
  protectionMode: MaxAvailability

  ## Specify the database SID to switchover thereby making it the primary.
  ## Switchover is not supported when fastStartFailover is true.
  setAsPrimaryDatabase: ""

  ## Enable/disable Fast-Start Failover for the dataguard configuration.
  fastStartFailover: false
